version: '2.0'
services:
  riemann_test:
    image: mnuessler/riemann
    container_name: riemann
    environment: []
    volumes:
      - "$PWD/riemann_config:/etc/riemann/"
    ports: ['5555:5555', '5555:5555/udp', '5556:5556', '5557:5557']
